### PR TITLE
All updates in one

### PR DESCRIPTION
**Pull request by SamuelNZ**
Merge to update repo to latest 'full' verison

### CODE REVIEW

**Comment by SamuelNZ** [comment]
Compiled version is 100mb smaller now.

Optimization OP.

**Comment by Psycho7** [comment]
Looks like you have done a lot of things. Great job! 👍

**Comment by SamuelNZ** [comment]
Ayy nah no credit to me, I've just been picking at the forks and branches and making small logic tweaks for speed while I learn Kotlin haha

Thanks to everyone who has contributed so far, Fuck the lurker who posted this on the forums

**Comment by SamuelNZ** [comment]
Ayy nah no credit to me, I've just been picking at the forks and branches and making small logic tweaks for speed while I learn Kotlin, was kinda painful picking through all these forks/branches though haha 

Contributors

These are the people who deserve your thanks

**Comment by al1m3rt** [comment]
can you add a download link of src while this is getting merged? i dont really want to add one by one

**Comment by BerkanYildiz** [comment]
@al1m3rt https://github.com/AiYinZiLeGong/PUBG-Radar/archive/532236e3a6e4dcc3ef40ce9b031a2bcf6d073115.zip

**Comment by al1m3rt** [comment]
thanks m8

**Comment by al1m3rt** [comment]
map is not cropped because opengl is disabled so we cant use the draw grid function? i am going to photoshop textures i think

**Comment by SamuelNZ** [comment]
Is the grid the only thing that was using opengl3? I wouldn't know, Completely deleted the grid because it looked ridiculous at certain zooms.

**Pull request closed without merging**
